all: janus.class


janus.class: janusParser.java janus.java janusDecFun.java genereteCode.java janusWriteF.java janusWriteB.java janusExpWalker.java janusIfThenElseWalker.java janusLoopWalker.java forkDecProgram.java janusForkandjoinWalker.java forkInitForward.java forkInitReverse.java janusStructDeclare.java
	        javac janus*.java
